package org.bukkit;
public interface Sound {
 Sound BLOCK_BEACON_ACTIVATE = null;
 Sound BLOCK_BEACON_DEACTIVATE = null;
 Sound BLOCK_RESPAWN_ANCHOR_CHARGE = null;
 Sound BLOCK_SCULK_SENSOR_CLICKING = null;
 Sound ENTITY_WARDEN_HEARTBEAT = null;
 Sound ENTITY_FIREWORK_ROCKET_SHOOT = null;
 Sound ITEM_CROSSBOW_SHOOT = null;
 Sound ENTITY_FIREWORK_ROCKET_BLAST = null;
 Sound ENTITY_FIREWORK_ROCKET_LARGE_BLAST = null;
 Sound ENTITY_FIREWORK_ROCKET_BLAST_FAR = null;
 Sound ENTITY_GENERIC_EXPLODE = null;
}
